/*
 * Which stations are next to each other on the Underground, used to
 * tell players when a guess is close to the answer.
 *
 * Generated from TfL's open data (api.tfl.gov.uk, Line Route Sequence)
 * on 2026-10-09. Powered by TfL Open Data.
 */

const CONNECTIONS = {
    "Acton Town": ["Chiswick Park", "Ealing Common", "South Ealing", "Turnham Green"],
    "Aldgate": ["Liverpool Street", "Tower Hill"],
    "Aldgate East": ["Liverpool Street", "Tower Hill", "Whitechapel"],
    "Alperton": ["Park Royal", "Sudbury Town"],
    "Amersham": ["Chalfont & Latimer"],
    "Angel": ["King's Cross St. Pancras", "Old Street"],
    "Archway": ["Highgate", "Tufnell Park"],
    "Arnos Grove": ["Bounds Green", "Southgate"],
    "Arsenal": ["Finsbury Park", "Holloway Road"],
    "Baker Street": ["Bond Street", "Edgware Road", "Finchley Road", "Great Portland Street", "Marylebone", "Regent's Park", "St. John's Wood"],
    "Balham": ["Clapham South", "Tooting Bec"],
    "Bank": ["Liverpool Street", "London Bridge", "Moorgate", "St. Paul's", "Waterloo"],
    "Barbican": ["Farringdon", "Moorgate"],
    "Barking": ["East Ham", "Upney"],
    "Barkingside": ["Fairlop", "Newbury Park"],
    "Barons Court": ["Earl's Court", "Hammersmith", "West Kensington"],
    "Battersea Power Station": ["Nine Elms"],
    "Bayswater": ["Notting Hill Gate", "Paddington"],
    "Becontree": ["Dagenham Heathway", "Upney"],
    "Belsize Park": ["Chalk Farm", "Hampstead"],
    "Bermondsey": ["Canada Water", "London Bridge"],
    "Bethnal Green": ["Liverpool Street", "Mile End"],
    "Blackfriars": ["Mansion House", "Temple"],
    "Blackhorse Road": ["Tottenham Hale", "Walthamstow Central"],
    "Bond Street": ["Baker Street", "Green Park", "Marble Arch", "Oxford Circus"],
    "Borough": ["Elephant & Castle", "London Bridge"],
    "Boston Manor": ["Northfields", "Osterley"],
    "Bounds Green": ["Arnos Grove", "Wood Green"],
    "Bow Road": ["Bromley-by-Bow", "Mile End"],
    "Brent Cross": ["Golders Green", "Hendon Central"],
    "Brixton": ["Stockwell"],
    "Bromley-by-Bow": ["Bow Road", "West Ham"],
    "Buckhurst Hill": ["Loughton", "Woodford"],
    "Burnt Oak": ["Colindale", "Edgware"],
    "Caledonian Road": ["Holloway Road", "King's Cross St. Pancras"],
    "Camden Town": ["Chalk Farm", "Euston", "Kentish Town", "Mornington Crescent"],
    "Canada Water": ["Bermondsey", "Canary Wharf"],
    "Canary Wharf": ["Canada Water", "North Greenwich"],
    "Canning Town": ["North Greenwich", "West Ham"],
    "Cannon Street": ["Mansion House", "Monument"],
    "Canons Park": ["Queensbury", "Stanmore"],
    "Chalfont & Latimer": ["Amersham", "Chesham", "Chorleywood"],
    "Chalk Farm": ["Belsize Park", "Camden Town"],
    "Chancery Lane": ["Holborn", "St. Paul's"],
    "Charing Cross": ["Embankment", "Leicester Square", "Piccadilly Circus"],
    "Chesham": ["Chalfont & Latimer"],
    "Chigwell": ["Grange Hill", "Roding Valley"],
    "Chiswick Park": ["Acton Town", "Turnham Green"],
    "Chorleywood": ["Chalfont & Latimer", "Rickmansworth"],
    "Clapham Common": ["Clapham North", "Clapham South"],
    "Clapham North": ["Clapham Common", "Stockwell"],
    "Clapham South": ["Balham", "Clapham Common"],
    "Cockfosters": ["Oakwood"],
    "Colindale": ["Burnt Oak", "Hendon Central"],
    "Colliers Wood": ["South Wimbledon", "Tooting Broadway"],
    "Covent Garden": ["Holborn", "Leicester Square"],
    "Croxley": ["Moor Park", "Watford"],
    "Dagenham East": ["Dagenham Heathway", "Elm Park"],
    "Dagenham Heathway": ["Becontree", "Dagenham East"],
    "Debden": ["Loughton", "Theydon Bois"],
    "Dollis Hill": ["Neasden", "Willesden Green"],
    "Ealing Broadway": ["Ealing Common", "West Acton"],
    "Ealing Common": ["Acton Town", "Ealing Broadway", "North Ealing"],
    "Earl's Court": ["Barons Court", "Gloucester Road", "High Street Kensington", "Kensington (Olympia)", "West Brompton", "West Kensington"],
    "East Acton": ["North Acton", "White City"],
    "East Finchley": ["Finchley Central", "Highgate"],
    "East Ham": ["Barking", "Upton Park"],
    "East Putney": ["Putney Bridge", "Southfields"],
    "Eastcote": ["Rayners Lane", "Ruislip Manor"],
    "Edgware": ["Burnt Oak"],
    "Edgware Road": ["Baker Street", "Marylebone", "Paddington"],
    "Elephant & Castle": ["Borough", "Kennington", "Lambeth North"],
    "Elm Park": ["Dagenham East", "Hornchurch"],
    "Embankment": ["Charing Cross", "Temple", "Waterloo", "Westminster"],
    "Epping": ["Theydon Bois"],
    "Euston": ["Camden Town", "King's Cross St. Pancras", "Mornington Crescent", "Warren Street"],
    "Euston Square": ["Great Portland Street", "King's Cross St. Pancras"],
    "Fairlop": ["Barkingside", "Hainault"],
    "Farringdon": ["Barbican", "King's Cross St. Pancras"],
    "Finchley Central": ["East Finchley", "Mill Hill East", "West Finchley"],
    "Finchley Road": ["Baker Street", "Swiss Cottage", "Wembley Park", "West Hampstead", "Willesden Green"],
    "Finsbury Park": ["Arsenal", "Highbury & Islington", "Manor House", "Seven Sisters"],
    "Fulham Broadway": ["Parsons Green", "West Brompton"],
    "Gants Hill": ["Newbury Park", "Redbridge"],
    "Gloucester Road": ["Earl's Court", "High Street Kensington", "South Kensington"],
    "Golders Green": ["Brent Cross", "Hampstead"],
    "Goldhawk Road": ["Hammersmith", "Shepherd's Bush Market"],
    "Goodge Street": ["Tottenham Court Road", "Warren Street"],
    "Grange Hill": ["Chigwell", "Hainault"],
    "Great Portland Street": ["Baker Street", "Euston Square"],
    "Green Park": ["Bond Street", "Hyde Park Corner", "Oxford Circus", "Piccadilly Circus", "Victoria", "Westminster"],
    "Greenford": ["Northolt", "Perivale"],
    "Gunnersbury": ["Kew Gardens", "Turnham Green"],
    "Hainault": ["Fairlop", "Grange Hill"],
    "Hammersmith": ["Barons Court", "Goldhawk Road", "Ravenscourt Park", "Turnham Green"],
    "Hampstead": ["Belsize Park", "Golders Green"],
    "Hanger Lane": ["North Acton", "Perivale"],
    "Harlesden": ["Stonebridge Park", "Willesden Junction"],
    "Harrow & Wealdstone": ["Kenton"],
    "Harrow-on-the-Hill": ["North Harrow", "Northwick Park", "West Harrow"],
    "Hatton Cross": ["Heathrow Terminal 4", "Heathrow Terminals 2 & 3", "Hounslow West"],
    "Heathrow Terminal 4": ["Hatton Cross", "Heathrow Terminals 2 & 3"],
    "Heathrow Terminal 5": ["Heathrow Terminals 2 & 3"],
    "Heathrow Terminals 2 & 3": ["Hatton Cross", "Heathrow Terminal 4", "Heathrow Terminal 5"],
    "Hendon Central": ["Brent Cross", "Colindale"],
    "High Barnet": ["Totteridge & Whetstone"],
    "High Street Kensington": ["Earl's Court", "Gloucester Road", "Notting Hill Gate"],
    "Highbury & Islington": ["Finsbury Park", "King's Cross St. Pancras"],
    "Highgate": ["Archway", "East Finchley"],
    "Hillingdon": ["Ickenham", "Uxbridge"],
    "Holborn": ["Chancery Lane", "Covent Garden", "Russell Square", "Tottenham Court Road"],
    "Holland Park": ["Notting Hill Gate", "Shepherd's Bush"],
    "Holloway Road": ["Arsenal", "Caledonian Road"],
    "Hornchurch": ["Elm Park", "Upminster Bridge"],
    "Hounslow Central": ["Hounslow East", "Hounslow West"],
    "Hounslow East": ["Hounslow Central", "Osterley"],
    "Hounslow West": ["Hatton Cross", "Hounslow Central"],
    "Hyde Park Corner": ["Green Park", "Knightsbridge"],
    "Ickenham": ["Hillingdon", "Ruislip"],
    "Kennington": ["Elephant & Castle", "Nine Elms", "Oval", "Waterloo"],
    "Kensal Green": ["Queen's Park", "Willesden Junction"],
    "Kensington (Olympia)": ["Earl's Court"],
    "Kentish Town": ["Camden Town", "Tufnell Park"],
    "Kenton": ["Harrow & Wealdstone", "South Kenton"],
    "Kew Gardens": ["Gunnersbury", "Richmond"],
    "Kilburn": ["West Hampstead", "Willesden Green"],
    "Kilburn Park": ["Maida Vale", "Queen's Park"],
    "King's Cross St. Pancras": ["Angel", "Caledonian Road", "Euston", "Euston Square", "Farringdon", "Highbury & Islington", "Russell Square"],
    "Kingsbury": ["Queensbury", "Wembley Park"],
    "Knightsbridge": ["Hyde Park Corner", "South Kensington"],
    "Ladbroke Grove": ["Latimer Road", "Westbourne Park"],
    "Lambeth North": ["Elephant & Castle", "Waterloo"],
    "Lancaster Gate": ["Marble Arch", "Queensway"],
    "Latimer Road": ["Ladbroke Grove", "Wood Lane"],
    "Leicester Square": ["Charing Cross", "Covent Garden", "Piccadilly Circus", "Tottenham Court Road"],
    "Leyton": ["Leytonstone", "Stratford"],
    "Leytonstone": ["Leyton", "Snaresbrook", "Wanstead"],
    "Liverpool Street": ["Aldgate", "Aldgate East", "Bank", "Bethnal Green", "Moorgate"],
    "London Bridge": ["Bank", "Bermondsey", "Borough", "Southwark"],
    "Loughton": ["Buckhurst Hill", "Debden"],
    "Maida Vale": ["Kilburn Park", "Warwick Avenue"],
    "Manor House": ["Finsbury Park", "Turnpike Lane"],
    "Mansion House": ["Blackfriars", "Cannon Street"],
    "Marble Arch": ["Bond Street", "Lancaster Gate"],
    "Marylebone": ["Baker Street", "Edgware Road"],
    "Mile End": ["Bethnal Green", "Bow Road", "Stepney Green", "Stratford"],
    "Mill Hill East": ["Finchley Central"],
    "Monument": ["Cannon Street", "Tower Hill"],
    "Moor Park": ["Croxley", "Northwood", "Rickmansworth"],
    "Moorgate": ["Bank", "Barbican", "Liverpool Street", "Old Street"],
    "Morden": ["South Wimbledon"],
    "Mornington Crescent": ["Camden Town", "Euston"],
    "Neasden": ["Dollis Hill", "Wembley Park"],
    "Newbury Park": ["Barkingside", "Gants Hill"],
    "Nine Elms": ["Battersea Power Station", "Kennington"],
    "North Acton": ["East Acton", "Hanger Lane", "West Acton"],
    "North Ealing": ["Ealing Common", "Park Royal"],
    "North Greenwich": ["Canary Wharf", "Canning Town"],
    "North Harrow": ["Harrow-on-the-Hill", "Pinner"],
    "North Wembley": ["South Kenton", "Wembley Central"],
    "Northfields": ["Boston Manor", "South Ealing"],
    "Northolt": ["Greenford", "South Ruislip"],
    "Northwick Park": ["Harrow-on-the-Hill", "Preston Road"],
    "Northwood": ["Moor Park", "Northwood Hills"],
    "Northwood Hills": ["Northwood", "Pinner"],
    "Notting Hill Gate": ["Bayswater", "High Street Kensington", "Holland Park", "Queensway"],
    "Oakwood": ["Cockfosters", "Southgate"],
    "Old Street": ["Angel", "Moorgate"],
    "Osterley": ["Boston Manor", "Hounslow East"],
    "Oval": ["Kennington", "Stockwell"],
    "Oxford Circus": ["Bond Street", "Green Park", "Piccadilly Circus", "Regent's Park", "Tottenham Court Road", "Warren Street"],
    "Paddington": ["Bayswater", "Edgware Road", "Royal Oak", "Warwick Avenue"],
    "Park Royal": ["Alperton", "North Ealing"],
    "Parsons Green": ["Fulham Broadway", "Putney Bridge"],
    "Perivale": ["Greenford", "Hanger Lane"],
    "Piccadilly Circus": ["Charing Cross", "Green Park", "Leicester Square", "Oxford Circus"],
    "Pimlico": ["Vauxhall", "Victoria"],
    "Pinner": ["North Harrow", "Northwood Hills"],
    "Plaistow": ["Upton Park", "West Ham"],
    "Preston Road": ["Northwick Park", "Wembley Park"],
    "Putney Bridge": ["East Putney", "Parsons Green"],
    "Queen's Park": ["Kensal Green", "Kilburn Park"],
    "Queensbury": ["Canons Park", "Kingsbury"],
    "Queensway": ["Lancaster Gate", "Notting Hill Gate"],
    "Ravenscourt Park": ["Hammersmith", "Stamford Brook"],
    "Rayners Lane": ["Eastcote", "South Harrow", "West Harrow"],
    "Redbridge": ["Gants Hill", "Wanstead"],
    "Regent's Park": ["Baker Street", "Oxford Circus"],
    "Richmond": ["Kew Gardens"],
    "Rickmansworth": ["Chorleywood", "Moor Park"],
    "Roding Valley": ["Chigwell", "Woodford"],
    "Royal Oak": ["Paddington", "Westbourne Park"],
    "Ruislip": ["Ickenham", "Ruislip Manor"],
    "Ruislip Gardens": ["South Ruislip", "West Ruislip"],
    "Ruislip Manor": ["Eastcote", "Ruislip"],
    "Russell Square": ["Holborn", "King's Cross St. Pancras"],
    "Seven Sisters": ["Finsbury Park", "Tottenham Hale"],
    "Shepherd's Bush": ["Holland Park", "White City"],
    "Shepherd's Bush Market": ["Goldhawk Road", "Wood Lane"],
    "Sloane Square": ["South Kensington", "Victoria"],
    "Snaresbrook": ["Leytonstone", "South Woodford"],
    "South Ealing": ["Acton Town", "Northfields"],
    "South Harrow": ["Rayners Lane", "Sudbury Hill"],
    "South Kensington": ["Gloucester Road", "Knightsbridge", "Sloane Square"],
    "South Kenton": ["Kenton", "North Wembley"],
    "South Ruislip": ["Northolt", "Ruislip Gardens"],
    "South Wimbledon": ["Colliers Wood", "Morden"],
    "South Woodford": ["Snaresbrook", "Woodford"],
    "Southfields": ["East Putney", "Wimbledon Park"],
    "Southgate": ["Arnos Grove", "Oakwood"],
    "Southwark": ["London Bridge", "Waterloo"],
    "St. James's Park": ["Victoria", "Westminster"],
    "St. John's Wood": ["Baker Street", "Swiss Cottage"],
    "St. Paul's": ["Bank", "Chancery Lane"],
    "Stamford Brook": ["Ravenscourt Park", "Turnham Green"],
    "Stanmore": ["Canons Park"],
    "Stepney Green": ["Mile End", "Whitechapel"],
    "Stockwell": ["Brixton", "Clapham North", "Oval", "Vauxhall"],
    "Stonebridge Park": ["Harlesden", "Wembley Central"],
    "Stratford": ["Leyton", "Mile End", "West Ham"],
    "Sudbury Hill": ["South Harrow", "Sudbury Town"],
    "Sudbury Town": ["Alperton", "Sudbury Hill"],
    "Swiss Cottage": ["Finchley Road", "St. John's Wood"],
    "Temple": ["Blackfriars", "Embankment"],
    "Theydon Bois": ["Debden", "Epping"],
    "Tooting Bec": ["Balham", "Tooting Broadway"],
    "Tooting Broadway": ["Colliers Wood", "Tooting Bec"],
    "Tottenham Court Road": ["Goodge Street", "Holborn", "Leicester Square", "Oxford Circus"],
    "Tottenham Hale": ["Blackhorse Road", "Seven Sisters"],
    "Totteridge & Whetstone": ["High Barnet", "Woodside Park"],
    "Tower Hill": ["Aldgate", "Aldgate East", "Monument"],
    "Tufnell Park": ["Archway", "Kentish Town"],
    "Turnham Green": ["Acton Town", "Chiswick Park", "Gunnersbury", "Hammersmith", "Stamford Brook"],
    "Turnpike Lane": ["Manor House", "Wood Green"],
    "Upminster": ["Upminster Bridge"],
    "Upminster Bridge": ["Hornchurch", "Upminster"],
    "Upney": ["Barking", "Becontree"],
    "Upton Park": ["East Ham", "Plaistow"],
    "Uxbridge": ["Hillingdon"],
    "Vauxhall": ["Pimlico", "Stockwell"],
    "Victoria": ["Green Park", "Pimlico", "Sloane Square", "St. James's Park"],
    "Walthamstow Central": ["Blackhorse Road"],
    "Wanstead": ["Leytonstone", "Redbridge"],
    "Warren Street": ["Euston", "Goodge Street", "Oxford Circus"],
    "Warwick Avenue": ["Maida Vale", "Paddington"],
    "Waterloo": ["Bank", "Embankment", "Kennington", "Lambeth North", "Southwark", "Westminster"],
    "Watford": ["Croxley"],
    "Wembley Central": ["North Wembley", "Stonebridge Park"],
    "Wembley Park": ["Finchley Road", "Kingsbury", "Neasden", "Preston Road", "Willesden Green"],
    "West Acton": ["Ealing Broadway", "North Acton"],
    "West Brompton": ["Earl's Court", "Fulham Broadway"],
    "West Finchley": ["Finchley Central", "Woodside Park"],
    "West Ham": ["Bromley-by-Bow", "Canning Town", "Plaistow", "Stratford"],
    "West Hampstead": ["Finchley Road", "Kilburn"],
    "West Harrow": ["Harrow-on-the-Hill", "Rayners Lane"],
    "West Kensington": ["Barons Court", "Earl's Court"],
    "West Ruislip": ["Ruislip Gardens"],
    "Westbourne Park": ["Ladbroke Grove", "Royal Oak"],
    "Westminster": ["Embankment", "Green Park", "St. James's Park", "Waterloo"],
    "White City": ["East Acton", "Shepherd's Bush"],
    "Whitechapel": ["Aldgate East", "Stepney Green"],
    "Willesden Green": ["Dollis Hill", "Finchley Road", "Kilburn", "Wembley Park"],
    "Willesden Junction": ["Harlesden", "Kensal Green"],
    "Wimbledon": ["Wimbledon Park"],
    "Wimbledon Park": ["Southfields", "Wimbledon"],
    "Wood Green": ["Bounds Green", "Turnpike Lane"],
    "Wood Lane": ["Latimer Road", "Shepherd's Bush Market"],
    "Woodford": ["Buckhurst Hill", "Roding Valley", "South Woodford"],
    "Woodside Park": ["Totteridge & Whetstone", "West Finchley"]
};
